# Generated by Django 5.1.6 on 2025-02-23 19:09

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the product.', max_length=1000)),
                ('image', cloudinary.models.CloudinaryField(help_text='The image of the product.', max_length=255, verbose_name='image')),
                ('product_url', models.URLField(help_text="The URL of the product's page.", max_length=1000)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='The cost price of the product.', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='The selling price of the product.', max_digits=10)),
                ('reviews', models.PositiveIntegerField(blank=True, default=0, help_text='The number of reviews the product has received.', null=True)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='The average star rating of the product.', max_digits=3, null=True)),
                ('is_best_seller', models.BooleanField(blank=True, default=False, help_text='Indicates whether the product is a bestseller.', null=True)),
                ('quantity', models.PositiveIntegerField(help_text='The available quantity of the product in stock.')),
                ('category', models.ForeignKey(help_text='The category to which the product belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders_api.product')),
            ],
        ),
    ]
