# Generated by Django 5.1.6 on 2025-02-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
