# Generated by Django 5.1.6 on 2025-02-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.PositiveIntegerField(blank=True, help_text='The number of reviews the product has received.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The average star rating of the product.', max_digits=3, null=True),
        ),
    ]
