# Generated by Django 5.1.6 on 2025-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0008_alter_product_reviews_alter_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates whether the product is a bestseller.', null=True),
        ),
    ]
